name: cst8918a03infra
description: A Remix app deployed with the Azure Container App service
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
